### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by me7** [mratsim/trace-of-radiance#5]
Hi,
  Just come here to mention that first time I cannot compile your program (refer to readme)
What I have to do is add --threads:on to command line
  You may edit the readme to help other people not face the same problem as me
![image](https://user-images.githubusercontent.com/10399270/83389624-b621e100-a41a-11ea-99bd-775da7644133.png)

**Comment by mratsim** [comment]
I probably should release a new version of Weave as well.

Weave devels currently tells you explicitly when `--threads:on` is missing.
